// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJIGDj4dyEO1jvaeqYdOlQ94gxsiC3uM',
    appId: '1:385228954319:web:fc8f1274ac09248602f5ba',
    messagingSenderId: '385228954319',
    projectId: 'skinskan-bd07b',
    authDomain: 'skinskan-bd07b.firebaseapp.com',
    storageBucket: 'skinskan-bd07b.appspot.com',
    measurementId: 'G-E4PBT7R4SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPj7T30WfyzQMr-1-HTM7JBpwX7_lqj8',
    appId: '1:385228954319:android:9c16cdcee7c3183202f5ba',
    messagingSenderId: '385228954319',
    projectId: 'skinskan-bd07b',
    storageBucket: 'skinskan-bd07b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Y4ROPFL7JHx0AjNoOblqPsCfxg6m9U4',
    appId: '1:385228954319:ios:3a49444e84ffd83402f5ba',
    messagingSenderId: '385228954319',
    projectId: 'skinskan-bd07b',
    storageBucket: 'skinskan-bd07b.appspot.com',
    iosBundleId: 'com.example.skinSkanV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Y4ROPFL7JHx0AjNoOblqPsCfxg6m9U4',
    appId: '1:385228954319:ios:3a49444e84ffd83402f5ba',
    messagingSenderId: '385228954319',
    projectId: 'skinskan-bd07b',
    storageBucket: 'skinskan-bd07b.appspot.com',
    iosBundleId: 'com.example.skinSkanV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiJIGDj4dyEO1jvaeqYdOlQ94gxsiC3uM',
    appId: '1:385228954319:web:65cc62e1260cd37502f5ba',
    messagingSenderId: '385228954319',
    projectId: 'skinskan-bd07b',
    authDomain: 'skinskan-bd07b.firebaseapp.com',
    storageBucket: 'skinskan-bd07b.appspot.com',
    measurementId: 'G-537486TKZD',
  );
}
